apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: react-app
          namespace: default
        spec:
          replicas: 3
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 0
          selector:
            matchLabels:
              app: react-app
          template:
            metadata:
              labels:
                app: react-app
            spec:
              containers:
              - name: react-app
                image: ${{ secrets.REGISTRY_NAME }}.azurecr.io/react-app:${{ github.sha }}
                ports:
                - containerPort: 80
                resources:
                  limits:
                    cpu: "500m"
                    memory: "512Mi"
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                livenessProbe:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 10
                  periodSeconds: 5
                readinessProbe:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 5
                  periodSeconds: 5