#cloud-config
package_upgrade: true
packages:
  - docker.io
  - docker-compose
runcmd:
  - systemctl enable docker
  - systemctl start docker
  - mkdir -p /var/app
  - docker login myimagerepo.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password $(az acr login --name myimagerepo --expose-token --output tsv --query accessToken)