name: Deploy to AKS Serverless

on:
  push:
    branches:
      - aksremote

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.REGISTRY_NAME }} --expose-token

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/react-app:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/react-app:${{ github.sha }}

      - name: Setup Kubernetes
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER_NAME }} \
            --overwrite-existing
          
          az aks update -n ${{ secrets.AKS_CLUSTER_NAME }} \
            -g ${{ secrets.AKS_RESOURCE_GROUP }} \
            --attach-acr ${{ secrets.REGISTRY_NAME }}

      - name: Deploy to Kubernetes
        run: |
          # Update image in deployment.yaml
          IMAGE="${{ secrets.REGISTRY_NAME }}.azurecr.io/react-app:${{ github.sha }}"
          sed -i "s|image: .*|image: $IMAGE|g" deployment.yaml
          
          # Apply configuration
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          
          # Verify deployment
          kubectl rollout status deployment/react-app -n default --timeout=180s
          kubectl get pods -n default

      - name: Slack Notification Success
        if: success()
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": ":white_check_mark: *Deployment Succeeded* \n*Environment*: AKS Serverless \n*Commit*: ${{ github.sha }} \n*By*: ${{ github.actor }} \n*Logs*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "channel": "ecs-fargate-deployment-notifications"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack Notification Failure
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": ":x: *Deployment Failed* \n*Environment*: AKS Serverless \n*Commit*: ${{ github.sha }} \n*By*: ${{ github.actor }} \n*Logs*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "channel": "ecs-fargate-deployment-notifications"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
