name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Green environment
      run: |
        ssh ubuntu@43.205.147.204 'git clone https://github.com/ramzan118/TextUtility1.git && cd TextUtility1 && ./deploy.sh'

    - name: Run tests
      run: |
        curl http://niete-test-lb-65841074.ap-south-1.elb.amazonaws.com/

    - name: Switch to Green environment
      run: |
        ssh ubuntu@13.126.111.139 'git clone https://github.com/ramzan118/TextUtility1.git && cd TextUtility1 && ./deploy.sh'
